//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class collect_request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public collect_request()
        {
            this.collect_reqest_details = new HashSet<collect_reqest_details>();
            this.food_distribution = new HashSet<food_distribution>();
        }
    
        public int id { get; set; }
        public string food_description { get; set; }
        public string quantity { get; set; }
        public System.DateTime expire_time { get; set; }
        public string status { get; set; }
        public string address { get; set; }
        public int food_donor_id { get; set; }
        public string preferred_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<collect_reqest_details> collect_reqest_details { get; set; }
        public virtual food_donor food_donor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<food_distribution> food_distribution { get; set; }
    }
}
