//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class food_distribution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public food_distribution()
        {
            this.food_distribution_details = new HashSet<food_distribution_details>();
        }
    
        public int id { get; set; }
        public string address { get; set; }
        public System.DateTime time { get; set; }
        public string beneficiary_count { get; set; }
        public int collect_request_id { get; set; }
        public string status { get; set; }
    
        public virtual collect_request collect_request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<food_distribution_details> food_distribution_details { get; set; }
    }
}
