//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zerohungerEntities3 : DbContext
    {
        public zerohungerEntities3()
            : base("name=zerohungerEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<collect_reqest_details> collect_reqest_details { get; set; }
        public virtual DbSet<collect_request> collect_request { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<food_distribution> food_distribution { get; set; }
        public virtual DbSet<food_distribution_details> food_distribution_details { get; set; }
        public virtual DbSet<food_donor> food_donor { get; set; }
    }
}
